# Generated by Django 3.0.7 on 2020-07-09 09:51

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(blank=True, default='default-banner.jpg', upload_to='media_pics/%Y/%m/%d')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('summary', models.CharField(max_length=200)),
                ('outsourced_news_link', models.CharField(blank=True, help_text="If you choose to enter outsourced news link (referencing news from another website), there's no need to type anything in the Body section", max_length=200, null=True)),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
