# Generated by Django 3.0.8 on 2020-08-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0003_auto_20200806_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='consent_to_share_my_information',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='consent_to_view_my_bookmarks',
            field=models.BooleanField(default=False),
        ),
    ]
