# Generated by Django 3.0.8 on 2020-08-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0004_auto_20200812_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='consent_to_share_my_information',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='consent_to_view_my_bookmarks',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
