# Generated by Django 3.0.8 on 2020-08-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0005_auto_20200812_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='consent_to_share_my_information',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='consent_to_view_my_bookmarks',
            field=models.BooleanField(default=False),
        ),
    ]
